omroep:
  fields:
    tuner:
      required: false
      selector:
        config_entry:
          integration: btx_omroep
    bericht:
      required: false
      selector:
        media:
          accept:
            - audio/*
    tekst:
      required: false
      selector:
        text:
          multiline: true
    muziekje:
      required: false
      selector:
        boolean:
    volume:
      required: false
      default: 32
      selector:
        number:
          min: 0
          max: 32
          mode: slider
    herhalingen:
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 10
          mode: slider
    pauze:
      required: false
      default: 1
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: s
          mode: box
